services:
  - type: web
    name: zero-email
    env: docker
    dockerfilePath: ./apps/mail/Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: WRANGLER_ENV
        value: render
    healthCheckPath: /
    autoDeploy: true
    buildCommand: pnpm install --frozen-lockfile && cd apps/mail && WRANGLER_ENV=render pnpm run build
    startCommand: cd apps/mail && NODE_ENV=production pnpm run start