import { paraglideVitePlugin } from '@inlang/paraglide-js';
import { cloudflare } from '@cloudflare/vite-plugin';
import { reactRouter } from '@react-router/dev/vite';
import tsconfigPaths from 'vite-tsconfig-paths';
import oxlintPlugin from 'vite-plugin-oxlint';
import babel from 'vite-plugin-babel';
import tailwindcss from 'tailwindcss';
import { defineConfig } from 'vite';
import dedent from 'dedent';

const ReactCompilerConfig = {
  /* ... */
};

export default defineConfig({
      define: {
      'import.meta.env.VITE_PUBLIC_BACKEND_URL': JSON.stringify('https://infflow-api-production.prabhatravib.workers.dev'),
      'import.meta.env.VITE_PUBLIC_APP_URL': JSON.stringify('https://infflow.prabhatravib.workers.dev'),
  },
  plugins: [
    oxlintPlugin(),
    reactRouter(),
    cloudflare({
      environments: {
        production: {
          name: 'zero-production',
          vars: {
              VITE_PUBLIC_BACKEND_URL: 'https://infflow-api-production.prabhatravib.workers.dev',
              VITE_PUBLIC_APP_URL: 'https://infflow.prabhatravib.workers.dev',
          },
        },
      },
      env: process.env.NODE_ENV === 'production' ? 'production' : 'local',
    }),
    babel({
      filter: /\.[jt]sx?$/,
      babelConfig: {
        presets: ['@babel/preset-typescript'], // if you use TypeScript
        plugins: [['babel-plugin-react-compiler', ReactCompilerConfig]],
      },
    }),
    tsconfigPaths(),
    {
      name: 'add-headers',
      applyToEnvironment: (env) => env.name === 'client',
      generateBundle() {
        this.emitFile({
          fileName: '_headers',
          type: 'asset',
          source: dedent`
            # Autogenerated

            /assets/*
              ! Cache-Control
                Cache-Control: public, immutable, max-age=31536000
          `,
        });
      },
    },
    paraglideVitePlugin({
      project: './project.inlang',
      outdir: './paraglide',
      strategy: ['cookie', 'baseLocale'],
    }),
  ],
  server: {
    port: 3000,
    warmup: {
      clientFiles: ['./app/**/*', './components/**/*'],
    },
  },
  css: {
    postcss: {
      plugins: [tailwindcss()],
    },
  },
  //   ssr: {
  //     optimizeDeps: {
  //       include: ['novel', '@tiptap/extension-placeholder'],
  //     },
  //   },
  esbuild: {
    pure: ['console.log'],
  },
  build: {
    sourcemap: false,
  },
  resolve: {
    alias: {
      tslib: 'tslib/tslib.es6.js',
    },
  },
});
